/** Villages served by the dealership (Jasdan / Vinchhiya belt). */
export const VILLAGES = [
  "Adhiya",
  "Ajmer",
  "Ambardi",
  "Amrapur",
  "Ankadiya",
  "Asalpar",
  "Atkot",
  "Bakhalvad",
  "Baldhoi",
  "Bandhali",
  "Barvala",
  "Belda",
  "Bhadla",
  "Bhadli",
  "Bhandariya",
  "Bhonyra",
  "Boghravadar",
  "Chhasiya",
  "Chitaliya",
  "Dadli",
  "Dahinsara",
  "Devdhari",
  "Devpara",
  "Dhedhuki",
  "Dodiyala",
  "Dolatpar",
  "Fulzar",
  "Gadhadiya (Jam)",
  "Gadhadiya (Jas)",
  "Gadhala",
  "Godladhar",
  "Gokhlana",
  "Gundala (Jas)",
  "Gundala Jam",
  "Hadmatiya khanda",
  "Hathasani",
  "Hingolgadh",
  "Ishvariya",
  "Janada",
  "Jangvad",
  "Jasapar",
  "Jasdan (M)",
  "Jivapar",
  "Juna Pipaliya",
  "Kaduka",
  "Kalasar",
  "Kamlapur",
  "Kandhevaliya",
  "Kanesara",
  "Kanpar",
  "Kansloliya",
  "Khadkana",
  "Khadvavdi",
  "Kharachiya Jam",
  "Kharachiya Jas",
  "Kotda",
  "Kothi",
  "Kundani",
  "Lalavadar",
  "Lilapur",
  "Madava",
  "Madhavipur",
  "Madhda",
  "Meghpar",
  "Modhuka",
  "Mota Hadmatiya",
  "Mota Matra",
  "Moti Lakhavad",
  "Nani Lakhavad",
  "Navagam",
  "Panchavada",
  "Parewala",
  "Patiyali",
  "Pipardi",
  "Polarpar",
  "Pratappur",
  "Raja Vadla Jam",
  "Rajavadla Jas",
  "Ramaliya",
  "Raningpar",
  "Ranjitgadh",
  "Ranparda",
  "Revaniya",
  "Rupavati",
  "Sanala",
  "Sanali",
  "Sanathali",
  "Sartanpar",
  "Shivrajpur",
  "Som Pipaliya",
  "Somalpar",
  "Thoriyali",
  "Vadod",
  "Vanala",
  "Vangadhara",
  "Veraval Bhadla",
  "Veraval Bhadli",
  "Veraval sanathali",
  "Vinchhiya",
  "Virnagar",
  "Virpur",
  "Zundala",
] as const;

/** Tehsil / taluka options. */
export const TEHSILS = ["Jasdan", "Vinchiya", "Other"] as const;
