/** Villages served by the dealership (Jasdan / Vinchhiya belt). */
export const VILLAGES = [
  "Adhiya",
  "Ajmer",
  "Ambardi",
  "Amrapur",
  "Ankadiya",
  "Asalpar",
  "Atkot",
  "Bakhalvad",
  "Baldhoi",
  "Bandhali",
  "Barvala",
  "Belda",
  "Bhadla",
  "Bhadli",
  "Bhandariya",
  "Bhonyra",
  "Boghravadar",
  "Chhasiya",
  "Chitaliya",
  "Dadli",
  "Dahinsara",
  "Devdhari",
  "Devpara",
  "Dhedhuki",
  "Dodiyala",
  "Dolatpar",
  "Fulzar",
  "Gadhadiya (Jam)",
  "Gadhadiya (Jas)",
  "Gadhala",
  "Godladhar",
  "Gokhlana",
  "Gundala (Jas)",
  "Gundala Jam",
  "Hadmatiya khanda",
  "Hathasani",
  "Hingolgadh",
  "Ishvariya",
  "Janada",
  "Jangvad",
  "Jasapar",
  "Jasdan (M)",
  "Jivapar",
  "Juna Pipaliya",
  "Kaduka",
  "Kalasar",
  "Kamlapur",
  "Kandhevaliya",
  "Kanesara",
  "Kanpar",
  "Kansloliya",
  "Khadkana",
  "Khadvavdi",
  "Kharachiya Jam",
  "Kharachiya Jas",
  "Kotda",
  "Kothi",
  "Kundani",
  "Lalavadar",
  "Lilapur",
  "Madava",
  "Madhavipur",
  "Madhda",
  "Meghpar",
  "Modhuka",
  "Mota Hadmatiya",
  "Mota Matra",
  "Moti Lakhavad",
  "Nani Lakhavad",
  "Navagam",
  "Panchavada",
  "Parewala",
  "Patiyali",
  "Pipardi",
  "Polarpar",
  "Pratappur",
  "Raja Vadla Jam",
  "Rajavadla Jas",
  "Ramaliya",
  "Raningpar",
  "Ranjitgadh",
  "Ranparda",
  "Revaniya",
  "Rupavati",
  "Sanala",
  "Sanali",
  "Sanathali",
  "Sartanpar",
  "Shivrajpur",
  "Som Pipaliya",
  "Somalpar",
  "Thoriyali",
  "Vadod",
  "Vanala",
  "Vangadhara",
  "Veraval Bhadla",
  "Veraval Bhadli",
  "Veraval sanathali",
  "Vinchhiya",
  "Virnagar",
  "Virpur",
  "Zundala",
] as const;

/** Tehsil / taluka options. */
export const TEHSILS = ["Jasdan", "Vinchiya", "Other"] as const;

/** Default village → tehsil mapping (fallback when the village master is unavailable). */
export const VILLAGE_TEHSIL: Record<string, string> = {
  "Adhiya": "Jasdan",
  "Ajmer": "Vinchiya",
  "Ambardi": "Vinchiya",
  "Amrapur": "Vinchiya",
  "Ankadiya": "Vinchiya",
  "Asalpar": "Vinchiya",
  "Atkot": "Jasdan",
  "Bakhalvad": "Jasdan",
  "Baldhoi": "Jasdan",
  "Bandhali": "Vinchiya",
  "Barvala": "Jasdan",
  "Belda": "Vinchiya",
  "Bhadla": "Jasdan",
  "Bhadli": "Vinchiya",
  "Bhandariya": "Jasdan",
  "Bhonyra": "Vinchiya",
  "Boghravadar": "Jasdan",
  "Chhasiya": "Vinchiya",
  "Chitaliya": "Jasdan",
  "Dadli": "Vinchiya",
  "Dahinsara": "Jasdan",
  "Devdhari": "Vinchiya",
  "Devpara": "Jasdan",
  "Dhedhuki": "Vinchiya",
  "Dodiyala": "Jasdan",
  "Dolatpar": "Jasdan",
  "Fulzar": "Vinchiya",
  "Gadhadiya (Jam)": "Jasdan",
  "Gadhadiya (Jas)": "Jasdan",
  "Gadhala": "Vinchiya",
  "Godladhar": "Vinchiya",
  "Gokhlana": "Jasdan",
  "Gundala (Jas)": "Vinchiya",
  "Gundala Jam": "Jasdan",
  "Hadmatiya khanda": "Jasdan",
  "Hathasani": "Vinchiya",
  "Hingolgadh": "Vinchiya",
  "Ishvariya": "Jasdan",
  "Janada": "Vinchiya",
  "Jangvad": "Jasdan",
  "Jasapar": "Jasdan",
  "Jasdan (M)": "Jasdan",
  "Jivapar": "Jasdan",
  "Juna Pipaliya": "Jasdan",
  "Kaduka": "Vinchiya",
  "Kalasar": "Jasdan",
  "Kamlapur": "Jasdan",
  "Kandhevaliya": "Vinchiya",
  "Kanesara": "Jasdan",
  "Kanpar": "Jasdan",
  "Kansloliya": "Vinchiya",
  "Khadkana": "Vinchiya",
  "Khadvavdi": "Jasdan",
  "Kharachiya Jam": "Jasdan",
  "Kharachiya Jas": "Vinchiya",
  "Kotda": "Vinchiya",
  "Kothi": "Jasdan",
  "Kundani": "Jasdan",
  "Lalavadar": "Vinchiya",
  "Lilapur": "Jasdan",
  "Madava": "Vinchiya",
  "Madhavipur": "Jasdan",
  "Madhda": "Jasdan",
  "Meghpar": "Jasdan",
  "Modhuka": "Vinchiya",
  "Mota Hadmatiya": "Vinchiya",
  "Mota Matra": "Vinchiya",
  "Moti Lakhavad": "Vinchiya",
  "Nani Lakhavad": "Jasdan",
  "Navagam": "Vinchiya",
  "Panchavada": "Jasdan",
  "Parewala": "Jasdan",
  "Patiyali": "Vinchiya",
  "Pipardi": "Vinchiya",
  "Polarpar": "Jasdan",
  "Pratappur": "Jasdan",
  "Raja Vadla Jam": "Jasdan",
  "Rajavadla Jas": "Jasdan",
  "Ramaliya": "Jasdan",
  "Raningpar": "Jasdan",
  "Ranjitgadh": "Jasdan",
  "Ranparda": "Jasdan",
  "Revaniya": "Vinchiya",
  "Rupavati": "Vinchiya",
  "Sanala": "Vinchiya",
  "Sanali": "Vinchiya",
  "Sanathali": "Jasdan",
  "Sartanpar": "Vinchiya",
  "Shivrajpur": "Jasdan",
  "Som Pipaliya": "Vinchiya",
  "Somalpar": "Vinchiya",
  "Thoriyali": "Vinchiya",
  "Vadod": "Vinchiya",
  "Vanala": "Vinchiya",
  "Vangadhara": "Vinchiya",
  "Veraval Bhadla": "Jasdan",
  "Veraval Bhadli": "Vinchiya",
  "Veraval sanathali": "Jasdan",
  "Vinchhiya": "Vinchiya",
  "Virnagar": "Jasdan",
  "Virpur": "Jasdan",
  "Zundala": "Jasdan",
};

export function tehsilForVillage(village: string): string | undefined {
  return VILLAGE_TEHSIL[village];
}
