/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedPayrollRouteImport } from './routes/_authenticated/payroll'
import { Route as AuthenticatedPerformanceRouteImport } from './routes/_authenticated/performance'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedAccountingIndexRouteImport } from './routes/_authenticated/accounting/index'
import { Route as AuthenticatedAccountingCustomerIdRouteImport } from './routes/_authenticated/accounting/$customerId'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedBookingsBookingIdRouteImport } from './routes/_authenticated/bookings/$bookingId'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings/new'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers/$customerId'
import { Route as AuthenticatedDeliveryIndexRouteImport } from './routes/_authenticated/delivery/index'
import { Route as AuthenticatedDeliveryBookingIdRouteImport } from './routes/_authenticated/delivery/$bookingId'
import { Route as AuthenticatedImportIndexRouteImport } from './routes/_authenticated/import/index'
import { Route as AuthenticatedInquiriesIndexRouteImport } from './routes/_authenticated/inquiries/index'
import { Route as AuthenticatedInquiriesInquiryIdRouteImport } from './routes/_authenticated/inquiries/$inquiryId'
import { Route as AuthenticatedInquiriesNewRouteImport } from './routes/_authenticated/inquiries/new'
import { Route as AuthenticatedPassingIndexRouteImport } from './routes/_authenticated/passing/index'
import { Route as AuthenticatedPassingBookingIdRouteImport } from './routes/_authenticated/passing/$bookingId'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedServiceIndexRouteImport } from './routes/_authenticated/service/index'
import { Route as AuthenticatedServiceJobIdRouteImport } from './routes/_authenticated/service/$jobId'
import { Route as AuthenticatedServiceJobcardsRouteImport } from './routes/_authenticated/service/jobcards'
import { Route as AuthenticatedServiceNewRouteImport } from './routes/_authenticated/service/new'
import { Route as AuthenticatedServiceRoutesRouteImport } from './routes/_authenticated/service/routes'
import { Route as AuthenticatedSparesIndexRouteImport } from './routes/_authenticated/spares/index'
import { Route as AuthenticatedSparesRequestIdRouteImport } from './routes/_authenticated/spares/$requestId'
import { Route as AuthenticatedSparesNewRouteImport } from './routes/_authenticated/spares/new'
import { Route as AuthenticatedStockIndexRouteImport } from './routes/_authenticated/stock/index'
import { Route as AuthenticatedStockStockIdRouteImport } from './routes/_authenticated/stock/$stockId'
import { Route as AuthenticatedSubsidyIndexRouteImport } from './routes/_authenticated/subsidy/index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedVillagesIndexRouteImport } from './routes/_authenticated/villages/index'
import { Route as AuthenticatedPrintChallanBookingIdRouteImport } from './routes/_authenticated/print/challan.$bookingId'
import { Route as AuthenticatedPrintGatepassBookingIdRouteImport } from './routes/_authenticated/print/gatepass.$bookingId'
import { Route as AuthenticatedPrintInvoiceBookingIdRouteImport } from './routes/_authenticated/print/invoice.$bookingId'
import { Route as AuthenticatedPrintPassingSetBookingIdRouteImport } from './routes/_authenticated/print/passing-set.$bookingId'
import { Route as AuthenticatedPrintPayslipPayslipIdRouteImport } from './routes/_authenticated/print/payslip.$payslipId'
import { Route as AuthenticatedPrintReceiptPaymentIdRouteImport } from './routes/_authenticated/print/receipt.$paymentId'
import { Route as AuthenticatedPrintSubsidyFileBookingIdRouteImport } from './routes/_authenticated/print/subsidy-file.$bookingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPayrollRoute = AuthenticatedPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerformanceRoute =
  AuthenticatedPerformanceRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountingIndexRoute =
  AuthenticatedAccountingIndexRouteImport.update({
    id: '/accounting/',
    path: '/accounting/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountingCustomerIdRoute =
  AuthenticatedAccountingCustomerIdRouteImport.update({
    id: '/accounting/$customerId',
    path: '/accounting/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsBookingIdRoute =
  AuthenticatedBookingsBookingIdRouteImport.update({
    id: '/bookings/$bookingId',
    path: '/bookings/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryIndexRoute =
  AuthenticatedDeliveryIndexRouteImport.update({
    id: '/delivery/',
    path: '/delivery/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeliveryBookingIdRoute =
  AuthenticatedDeliveryBookingIdRouteImport.update({
    id: '/delivery/$bookingId',
    path: '/delivery/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportIndexRoute =
  AuthenticatedImportIndexRouteImport.update({
    id: '/import/',
    path: '/import/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiriesIndexRoute =
  AuthenticatedInquiriesIndexRouteImport.update({
    id: '/inquiries/',
    path: '/inquiries/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiriesInquiryIdRoute =
  AuthenticatedInquiriesInquiryIdRouteImport.update({
    id: '/inquiries/$inquiryId',
    path: '/inquiries/$inquiryId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInquiriesNewRoute =
  AuthenticatedInquiriesNewRouteImport.update({
    id: '/inquiries/new',
    path: '/inquiries/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPassingIndexRoute =
  AuthenticatedPassingIndexRouteImport.update({
    id: '/passing/',
    path: '/passing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPassingBookingIdRoute =
  AuthenticatedPassingBookingIdRouteImport.update({
    id: '/passing/$bookingId',
    path: '/passing/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceIndexRoute =
  AuthenticatedServiceIndexRouteImport.update({
    id: '/service/',
    path: '/service/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceJobIdRoute =
  AuthenticatedServiceJobIdRouteImport.update({
    id: '/service/$jobId',
    path: '/service/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceJobcardsRoute =
  AuthenticatedServiceJobcardsRouteImport.update({
    id: '/service/jobcards',
    path: '/service/jobcards',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedServiceNewRoute = AuthenticatedServiceNewRouteImport.update({
  id: '/service/new',
  path: '/service/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServiceRoutesRoute =
  AuthenticatedServiceRoutesRouteImport.update({
    id: '/service/routes',
    path: '/service/routes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSparesIndexRoute =
  AuthenticatedSparesIndexRouteImport.update({
    id: '/spares/',
    path: '/spares/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSparesRequestIdRoute =
  AuthenticatedSparesRequestIdRouteImport.update({
    id: '/spares/$requestId',
    path: '/spares/$requestId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSparesNewRoute = AuthenticatedSparesNewRouteImport.update({
  id: '/spares/new',
  path: '/spares/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockIndexRoute = AuthenticatedStockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStockStockIdRoute =
  AuthenticatedStockStockIdRouteImport.update({
    id: '/stock/$stockId',
    path: '/stock/$stockId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubsidyIndexRoute =
  AuthenticatedSubsidyIndexRouteImport.update({
    id: '/subsidy/',
    path: '/subsidy/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVillagesIndexRoute =
  AuthenticatedVillagesIndexRouteImport.update({
    id: '/villages/',
    path: '/villages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintChallanBookingIdRoute =
  AuthenticatedPrintChallanBookingIdRouteImport.update({
    id: '/print/challan/$bookingId',
    path: '/print/challan/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintGatepassBookingIdRoute =
  AuthenticatedPrintGatepassBookingIdRouteImport.update({
    id: '/print/gatepass/$bookingId',
    path: '/print/gatepass/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintInvoiceBookingIdRoute =
  AuthenticatedPrintInvoiceBookingIdRouteImport.update({
    id: '/print/invoice/$bookingId',
    path: '/print/invoice/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintPassingSetBookingIdRoute =
  AuthenticatedPrintPassingSetBookingIdRouteImport.update({
    id: '/print/passing-set/$bookingId',
    path: '/print/passing-set/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintPayslipPayslipIdRoute =
  AuthenticatedPrintPayslipPayslipIdRouteImport.update({
    id: '/print/payslip/$payslipId',
    path: '/print/payslip/$payslipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintReceiptPaymentIdRoute =
  AuthenticatedPrintReceiptPaymentIdRouteImport.update({
    id: '/print/receipt/$paymentId',
    path: '/print/receipt/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPrintSubsidyFileBookingIdRoute =
  AuthenticatedPrintSubsidyFileBookingIdRouteImport.update({
    id: '/print/subsidy-file/$bookingId',
    path: '/print/subsidy-file/$bookingId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/team': typeof AuthenticatedTeamRoute
  '/accounting/$customerId': typeof AuthenticatedAccountingCustomerIdRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery/$bookingId': typeof AuthenticatedDeliveryBookingIdRoute
  '/inquiries/$inquiryId': typeof AuthenticatedInquiriesInquiryIdRoute
  '/inquiries/new': typeof AuthenticatedInquiriesNewRoute
  '/passing/$bookingId': typeof AuthenticatedPassingBookingIdRoute
  '/service/$jobId': typeof AuthenticatedServiceJobIdRoute
  '/service/jobcards': typeof AuthenticatedServiceJobcardsRoute
  '/service/new': typeof AuthenticatedServiceNewRoute
  '/service/routes': typeof AuthenticatedServiceRoutesRoute
  '/spares/$requestId': typeof AuthenticatedSparesRequestIdRoute
  '/spares/new': typeof AuthenticatedSparesNewRoute
  '/stock/$stockId': typeof AuthenticatedStockStockIdRoute
  '/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/import/': typeof AuthenticatedImportIndexRoute
  '/inquiries/': typeof AuthenticatedInquiriesIndexRoute
  '/passing/': typeof AuthenticatedPassingIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/service/': typeof AuthenticatedServiceIndexRoute
  '/spares/': typeof AuthenticatedSparesIndexRoute
  '/stock/': typeof AuthenticatedStockIndexRoute
  '/subsidy/': typeof AuthenticatedSubsidyIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/villages/': typeof AuthenticatedVillagesIndexRoute
  '/print/challan/$bookingId': typeof AuthenticatedPrintChallanBookingIdRoute
  '/print/gatepass/$bookingId': typeof AuthenticatedPrintGatepassBookingIdRoute
  '/print/invoice/$bookingId': typeof AuthenticatedPrintInvoiceBookingIdRoute
  '/print/passing-set/$bookingId': typeof AuthenticatedPrintPassingSetBookingIdRoute
  '/print/payslip/$payslipId': typeof AuthenticatedPrintPayslipPayslipIdRoute
  '/print/receipt/$paymentId': typeof AuthenticatedPrintReceiptPaymentIdRoute
  '/print/subsidy-file/$bookingId': typeof AuthenticatedPrintSubsidyFileBookingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/payroll': typeof AuthenticatedPayrollRoute
  '/performance': typeof AuthenticatedPerformanceRoute
  '/team': typeof AuthenticatedTeamRoute
  '/accounting/$customerId': typeof AuthenticatedAccountingCustomerIdRoute
  '/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/delivery/$bookingId': typeof AuthenticatedDeliveryBookingIdRoute
  '/inquiries/$inquiryId': typeof AuthenticatedInquiriesInquiryIdRoute
  '/inquiries/new': typeof AuthenticatedInquiriesNewRoute
  '/passing/$bookingId': typeof AuthenticatedPassingBookingIdRoute
  '/service/$jobId': typeof AuthenticatedServiceJobIdRoute
  '/service/jobcards': typeof AuthenticatedServiceJobcardsRoute
  '/service/new': typeof AuthenticatedServiceNewRoute
  '/service/routes': typeof AuthenticatedServiceRoutesRoute
  '/spares/$requestId': typeof AuthenticatedSparesRequestIdRoute
  '/spares/new': typeof AuthenticatedSparesNewRoute
  '/stock/$stockId': typeof AuthenticatedStockStockIdRoute
  '/accounting': typeof AuthenticatedAccountingIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/delivery': typeof AuthenticatedDeliveryIndexRoute
  '/import': typeof AuthenticatedImportIndexRoute
  '/inquiries': typeof AuthenticatedInquiriesIndexRoute
  '/passing': typeof AuthenticatedPassingIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/service': typeof AuthenticatedServiceIndexRoute
  '/spares': typeof AuthenticatedSparesIndexRoute
  '/stock': typeof AuthenticatedStockIndexRoute
  '/subsidy': typeof AuthenticatedSubsidyIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/villages': typeof AuthenticatedVillagesIndexRoute
  '/print/challan/$bookingId': typeof AuthenticatedPrintChallanBookingIdRoute
  '/print/gatepass/$bookingId': typeof AuthenticatedPrintGatepassBookingIdRoute
  '/print/invoice/$bookingId': typeof AuthenticatedPrintInvoiceBookingIdRoute
  '/print/passing-set/$bookingId': typeof AuthenticatedPrintPassingSetBookingIdRoute
  '/print/payslip/$payslipId': typeof AuthenticatedPrintPayslipPayslipIdRoute
  '/print/receipt/$paymentId': typeof AuthenticatedPrintReceiptPaymentIdRoute
  '/print/subsidy-file/$bookingId': typeof AuthenticatedPrintSubsidyFileBookingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/payroll': typeof AuthenticatedPayrollRoute
  '/_authenticated/performance': typeof AuthenticatedPerformanceRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/accounting/$customerId': typeof AuthenticatedAccountingCustomerIdRoute
  '/_authenticated/bookings/$bookingId': typeof AuthenticatedBookingsBookingIdRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/delivery/$bookingId': typeof AuthenticatedDeliveryBookingIdRoute
  '/_authenticated/inquiries/$inquiryId': typeof AuthenticatedInquiriesInquiryIdRoute
  '/_authenticated/inquiries/new': typeof AuthenticatedInquiriesNewRoute
  '/_authenticated/passing/$bookingId': typeof AuthenticatedPassingBookingIdRoute
  '/_authenticated/service/$jobId': typeof AuthenticatedServiceJobIdRoute
  '/_authenticated/service/jobcards': typeof AuthenticatedServiceJobcardsRoute
  '/_authenticated/service/new': typeof AuthenticatedServiceNewRoute
  '/_authenticated/service/routes': typeof AuthenticatedServiceRoutesRoute
  '/_authenticated/spares/$requestId': typeof AuthenticatedSparesRequestIdRoute
  '/_authenticated/spares/new': typeof AuthenticatedSparesNewRoute
  '/_authenticated/stock/$stockId': typeof AuthenticatedStockStockIdRoute
  '/_authenticated/accounting/': typeof AuthenticatedAccountingIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/delivery/': typeof AuthenticatedDeliveryIndexRoute
  '/_authenticated/import/': typeof AuthenticatedImportIndexRoute
  '/_authenticated/inquiries/': typeof AuthenticatedInquiriesIndexRoute
  '/_authenticated/passing/': typeof AuthenticatedPassingIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/service/': typeof AuthenticatedServiceIndexRoute
  '/_authenticated/spares/': typeof AuthenticatedSparesIndexRoute
  '/_authenticated/stock/': typeof AuthenticatedStockIndexRoute
  '/_authenticated/subsidy/': typeof AuthenticatedSubsidyIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/villages/': typeof AuthenticatedVillagesIndexRoute
  '/_authenticated/print/challan/$bookingId': typeof AuthenticatedPrintChallanBookingIdRoute
  '/_authenticated/print/gatepass/$bookingId': typeof AuthenticatedPrintGatepassBookingIdRoute
  '/_authenticated/print/invoice/$bookingId': typeof AuthenticatedPrintInvoiceBookingIdRoute
  '/_authenticated/print/passing-set/$bookingId': typeof AuthenticatedPrintPassingSetBookingIdRoute
  '/_authenticated/print/payslip/$payslipId': typeof AuthenticatedPrintPayslipPayslipIdRoute
  '/_authenticated/print/receipt/$paymentId': typeof AuthenticatedPrintReceiptPaymentIdRoute
  '/_authenticated/print/subsidy-file/$bookingId': typeof AuthenticatedPrintSubsidyFileBookingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/hr'
    | '/payroll'
    | '/performance'
    | '/team'
    | '/accounting/$customerId'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/customers/$customerId'
    | '/delivery/$bookingId'
    | '/inquiries/$inquiryId'
    | '/inquiries/new'
    | '/passing/$bookingId'
    | '/service/$jobId'
    | '/service/jobcards'
    | '/service/new'
    | '/service/routes'
    | '/spares/$requestId'
    | '/spares/new'
    | '/stock/$stockId'
    | '/accounting/'
    | '/bookings/'
    | '/customers/'
    | '/delivery/'
    | '/import/'
    | '/inquiries/'
    | '/passing/'
    | '/products/'
    | '/service/'
    | '/spares/'
    | '/stock/'
    | '/subsidy/'
    | '/system/'
    | '/users/'
    | '/villages/'
    | '/print/challan/$bookingId'
    | '/print/gatepass/$bookingId'
    | '/print/invoice/$bookingId'
    | '/print/passing-set/$bookingId'
    | '/print/payslip/$payslipId'
    | '/print/receipt/$paymentId'
    | '/print/subsidy-file/$bookingId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/hr'
    | '/payroll'
    | '/performance'
    | '/team'
    | '/accounting/$customerId'
    | '/bookings/$bookingId'
    | '/bookings/new'
    | '/customers/$customerId'
    | '/delivery/$bookingId'
    | '/inquiries/$inquiryId'
    | '/inquiries/new'
    | '/passing/$bookingId'
    | '/service/$jobId'
    | '/service/jobcards'
    | '/service/new'
    | '/service/routes'
    | '/spares/$requestId'
    | '/spares/new'
    | '/stock/$stockId'
    | '/accounting'
    | '/bookings'
    | '/customers'
    | '/delivery'
    | '/import'
    | '/inquiries'
    | '/passing'
    | '/products'
    | '/service'
    | '/spares'
    | '/stock'
    | '/subsidy'
    | '/system'
    | '/users'
    | '/villages'
    | '/print/challan/$bookingId'
    | '/print/gatepass/$bookingId'
    | '/print/invoice/$bookingId'
    | '/print/passing-set/$bookingId'
    | '/print/payslip/$payslipId'
    | '/print/receipt/$paymentId'
    | '/print/subsidy-file/$bookingId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/hr'
    | '/_authenticated/payroll'
    | '/_authenticated/performance'
    | '/_authenticated/team'
    | '/_authenticated/accounting/$customerId'
    | '/_authenticated/bookings/$bookingId'
    | '/_authenticated/bookings/new'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/delivery/$bookingId'
    | '/_authenticated/inquiries/$inquiryId'
    | '/_authenticated/inquiries/new'
    | '/_authenticated/passing/$bookingId'
    | '/_authenticated/service/$jobId'
    | '/_authenticated/service/jobcards'
    | '/_authenticated/service/new'
    | '/_authenticated/service/routes'
    | '/_authenticated/spares/$requestId'
    | '/_authenticated/spares/new'
    | '/_authenticated/stock/$stockId'
    | '/_authenticated/accounting/'
    | '/_authenticated/bookings/'
    | '/_authenticated/customers/'
    | '/_authenticated/delivery/'
    | '/_authenticated/import/'
    | '/_authenticated/inquiries/'
    | '/_authenticated/passing/'
    | '/_authenticated/products/'
    | '/_authenticated/service/'
    | '/_authenticated/spares/'
    | '/_authenticated/stock/'
    | '/_authenticated/subsidy/'
    | '/_authenticated/system/'
    | '/_authenticated/users/'
    | '/_authenticated/villages/'
    | '/_authenticated/print/challan/$bookingId'
    | '/_authenticated/print/gatepass/$bookingId'
    | '/_authenticated/print/invoice/$bookingId'
    | '/_authenticated/print/passing-set/$bookingId'
    | '/_authenticated/print/payslip/$payslipId'
    | '/_authenticated/print/receipt/$paymentId'
    | '/_authenticated/print/subsidy-file/$bookingId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payroll': {
      id: '/_authenticated/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AuthenticatedPayrollRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/performance': {
      id: '/_authenticated/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthenticatedPerformanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/': {
      id: '/_authenticated/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AuthenticatedAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accounting/$customerId': {
      id: '/_authenticated/accounting/$customerId'
      path: '/accounting/$customerId'
      fullPath: '/accounting/$customerId'
      preLoaderRoute: typeof AuthenticatedAccountingCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$bookingId': {
      id: '/_authenticated/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof AuthenticatedBookingsBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery/': {
      id: '/_authenticated/delivery/'
      path: '/delivery'
      fullPath: '/delivery/'
      preLoaderRoute: typeof AuthenticatedDeliveryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/delivery/$bookingId': {
      id: '/_authenticated/delivery/$bookingId'
      path: '/delivery/$bookingId'
      fullPath: '/delivery/$bookingId'
      preLoaderRoute: typeof AuthenticatedDeliveryBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import/': {
      id: '/_authenticated/import/'
      path: '/import'
      fullPath: '/import/'
      preLoaderRoute: typeof AuthenticatedImportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries/': {
      id: '/_authenticated/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof AuthenticatedInquiriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries/$inquiryId': {
      id: '/_authenticated/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/inquiries/$inquiryId'
      preLoaderRoute: typeof AuthenticatedInquiriesInquiryIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inquiries/new': {
      id: '/_authenticated/inquiries/new'
      path: '/inquiries/new'
      fullPath: '/inquiries/new'
      preLoaderRoute: typeof AuthenticatedInquiriesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passing/': {
      id: '/_authenticated/passing/'
      path: '/passing'
      fullPath: '/passing/'
      preLoaderRoute: typeof AuthenticatedPassingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passing/$bookingId': {
      id: '/_authenticated/passing/$bookingId'
      path: '/passing/$bookingId'
      fullPath: '/passing/$bookingId'
      preLoaderRoute: typeof AuthenticatedPassingBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/': {
      id: '/_authenticated/service/'
      path: '/service'
      fullPath: '/service/'
      preLoaderRoute: typeof AuthenticatedServiceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/$jobId': {
      id: '/_authenticated/service/$jobId'
      path: '/service/$jobId'
      fullPath: '/service/$jobId'
      preLoaderRoute: typeof AuthenticatedServiceJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/jobcards': {
      id: '/_authenticated/service/jobcards'
      path: '/service/jobcards'
      fullPath: '/service/jobcards'
      preLoaderRoute: typeof AuthenticatedServiceJobcardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/new': {
      id: '/_authenticated/service/new'
      path: '/service/new'
      fullPath: '/service/new'
      preLoaderRoute: typeof AuthenticatedServiceNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/service/routes': {
      id: '/_authenticated/service/routes'
      path: '/service/routes'
      fullPath: '/service/routes'
      preLoaderRoute: typeof AuthenticatedServiceRoutesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spares/': {
      id: '/_authenticated/spares/'
      path: '/spares'
      fullPath: '/spares/'
      preLoaderRoute: typeof AuthenticatedSparesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spares/$requestId': {
      id: '/_authenticated/spares/$requestId'
      path: '/spares/$requestId'
      fullPath: '/spares/$requestId'
      preLoaderRoute: typeof AuthenticatedSparesRequestIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/spares/new': {
      id: '/_authenticated/spares/new'
      path: '/spares/new'
      fullPath: '/spares/new'
      preLoaderRoute: typeof AuthenticatedSparesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/': {
      id: '/_authenticated/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof AuthenticatedStockIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/stock/$stockId': {
      id: '/_authenticated/stock/$stockId'
      path: '/stock/$stockId'
      fullPath: '/stock/$stockId'
      preLoaderRoute: typeof AuthenticatedStockStockIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subsidy/': {
      id: '/_authenticated/subsidy/'
      path: '/subsidy'
      fullPath: '/subsidy/'
      preLoaderRoute: typeof AuthenticatedSubsidyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/villages/': {
      id: '/_authenticated/villages/'
      path: '/villages'
      fullPath: '/villages/'
      preLoaderRoute: typeof AuthenticatedVillagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/challan/$bookingId': {
      id: '/_authenticated/print/challan/$bookingId'
      path: '/print/challan/$bookingId'
      fullPath: '/print/challan/$bookingId'
      preLoaderRoute: typeof AuthenticatedPrintChallanBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/gatepass/$bookingId': {
      id: '/_authenticated/print/gatepass/$bookingId'
      path: '/print/gatepass/$bookingId'
      fullPath: '/print/gatepass/$bookingId'
      preLoaderRoute: typeof AuthenticatedPrintGatepassBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/invoice/$bookingId': {
      id: '/_authenticated/print/invoice/$bookingId'
      path: '/print/invoice/$bookingId'
      fullPath: '/print/invoice/$bookingId'
      preLoaderRoute: typeof AuthenticatedPrintInvoiceBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/passing-set/$bookingId': {
      id: '/_authenticated/print/passing-set/$bookingId'
      path: '/print/passing-set/$bookingId'
      fullPath: '/print/passing-set/$bookingId'
      preLoaderRoute: typeof AuthenticatedPrintPassingSetBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/payslip/$payslipId': {
      id: '/_authenticated/print/payslip/$payslipId'
      path: '/print/payslip/$payslipId'
      fullPath: '/print/payslip/$payslipId'
      preLoaderRoute: typeof AuthenticatedPrintPayslipPayslipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/receipt/$paymentId': {
      id: '/_authenticated/print/receipt/$paymentId'
      path: '/print/receipt/$paymentId'
      fullPath: '/print/receipt/$paymentId'
      preLoaderRoute: typeof AuthenticatedPrintReceiptPaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print/subsidy-file/$bookingId': {
      id: '/_authenticated/print/subsidy-file/$bookingId'
      path: '/print/subsidy-file/$bookingId'
      fullPath: '/print/subsidy-file/$bookingId'
      preLoaderRoute: typeof AuthenticatedPrintSubsidyFileBookingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedPayrollRoute: typeof AuthenticatedPayrollRoute
  AuthenticatedPerformanceRoute: typeof AuthenticatedPerformanceRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedAccountingCustomerIdRoute: typeof AuthenticatedAccountingCustomerIdRoute
  AuthenticatedBookingsBookingIdRoute: typeof AuthenticatedBookingsBookingIdRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedDeliveryBookingIdRoute: typeof AuthenticatedDeliveryBookingIdRoute
  AuthenticatedInquiriesInquiryIdRoute: typeof AuthenticatedInquiriesInquiryIdRoute
  AuthenticatedInquiriesNewRoute: typeof AuthenticatedInquiriesNewRoute
  AuthenticatedPassingBookingIdRoute: typeof AuthenticatedPassingBookingIdRoute
  AuthenticatedServiceJobIdRoute: typeof AuthenticatedServiceJobIdRoute
  AuthenticatedServiceJobcardsRoute: typeof AuthenticatedServiceJobcardsRoute
  AuthenticatedServiceNewRoute: typeof AuthenticatedServiceNewRoute
  AuthenticatedServiceRoutesRoute: typeof AuthenticatedServiceRoutesRoute
  AuthenticatedSparesRequestIdRoute: typeof AuthenticatedSparesRequestIdRoute
  AuthenticatedSparesNewRoute: typeof AuthenticatedSparesNewRoute
  AuthenticatedStockStockIdRoute: typeof AuthenticatedStockStockIdRoute
  AuthenticatedAccountingIndexRoute: typeof AuthenticatedAccountingIndexRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDeliveryIndexRoute: typeof AuthenticatedDeliveryIndexRoute
  AuthenticatedImportIndexRoute: typeof AuthenticatedImportIndexRoute
  AuthenticatedInquiriesIndexRoute: typeof AuthenticatedInquiriesIndexRoute
  AuthenticatedPassingIndexRoute: typeof AuthenticatedPassingIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedServiceIndexRoute: typeof AuthenticatedServiceIndexRoute
  AuthenticatedSparesIndexRoute: typeof AuthenticatedSparesIndexRoute
  AuthenticatedStockIndexRoute: typeof AuthenticatedStockIndexRoute
  AuthenticatedSubsidyIndexRoute: typeof AuthenticatedSubsidyIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVillagesIndexRoute: typeof AuthenticatedVillagesIndexRoute
  AuthenticatedPrintChallanBookingIdRoute: typeof AuthenticatedPrintChallanBookingIdRoute
  AuthenticatedPrintGatepassBookingIdRoute: typeof AuthenticatedPrintGatepassBookingIdRoute
  AuthenticatedPrintInvoiceBookingIdRoute: typeof AuthenticatedPrintInvoiceBookingIdRoute
  AuthenticatedPrintPassingSetBookingIdRoute: typeof AuthenticatedPrintPassingSetBookingIdRoute
  AuthenticatedPrintPayslipPayslipIdRoute: typeof AuthenticatedPrintPayslipPayslipIdRoute
  AuthenticatedPrintReceiptPaymentIdRoute: typeof AuthenticatedPrintReceiptPaymentIdRoute
  AuthenticatedPrintSubsidyFileBookingIdRoute: typeof AuthenticatedPrintSubsidyFileBookingIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedPayrollRoute: AuthenticatedPayrollRoute,
  AuthenticatedPerformanceRoute: AuthenticatedPerformanceRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedAccountingCustomerIdRoute:
    AuthenticatedAccountingCustomerIdRoute,
  AuthenticatedBookingsBookingIdRoute: AuthenticatedBookingsBookingIdRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedDeliveryBookingIdRoute: AuthenticatedDeliveryBookingIdRoute,
  AuthenticatedInquiriesInquiryIdRoute: AuthenticatedInquiriesInquiryIdRoute,
  AuthenticatedInquiriesNewRoute: AuthenticatedInquiriesNewRoute,
  AuthenticatedPassingBookingIdRoute: AuthenticatedPassingBookingIdRoute,
  AuthenticatedServiceJobIdRoute: AuthenticatedServiceJobIdRoute,
  AuthenticatedServiceJobcardsRoute: AuthenticatedServiceJobcardsRoute,
  AuthenticatedServiceNewRoute: AuthenticatedServiceNewRoute,
  AuthenticatedServiceRoutesRoute: AuthenticatedServiceRoutesRoute,
  AuthenticatedSparesRequestIdRoute: AuthenticatedSparesRequestIdRoute,
  AuthenticatedSparesNewRoute: AuthenticatedSparesNewRoute,
  AuthenticatedStockStockIdRoute: AuthenticatedStockStockIdRoute,
  AuthenticatedAccountingIndexRoute: AuthenticatedAccountingIndexRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDeliveryIndexRoute: AuthenticatedDeliveryIndexRoute,
  AuthenticatedImportIndexRoute: AuthenticatedImportIndexRoute,
  AuthenticatedInquiriesIndexRoute: AuthenticatedInquiriesIndexRoute,
  AuthenticatedPassingIndexRoute: AuthenticatedPassingIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedServiceIndexRoute: AuthenticatedServiceIndexRoute,
  AuthenticatedSparesIndexRoute: AuthenticatedSparesIndexRoute,
  AuthenticatedStockIndexRoute: AuthenticatedStockIndexRoute,
  AuthenticatedSubsidyIndexRoute: AuthenticatedSubsidyIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVillagesIndexRoute: AuthenticatedVillagesIndexRoute,
  AuthenticatedPrintChallanBookingIdRoute:
    AuthenticatedPrintChallanBookingIdRoute,
  AuthenticatedPrintGatepassBookingIdRoute:
    AuthenticatedPrintGatepassBookingIdRoute,
  AuthenticatedPrintInvoiceBookingIdRoute:
    AuthenticatedPrintInvoiceBookingIdRoute,
  AuthenticatedPrintPassingSetBookingIdRoute:
    AuthenticatedPrintPassingSetBookingIdRoute,
  AuthenticatedPrintPayslipPayslipIdRoute:
    AuthenticatedPrintPayslipPayslipIdRoute,
  AuthenticatedPrintReceiptPaymentIdRoute:
    AuthenticatedPrintReceiptPaymentIdRoute,
  AuthenticatedPrintSubsidyFileBookingIdRoute:
    AuthenticatedPrintSubsidyFileBookingIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
